<!DOCTYPE html>
<?php 
$title = "FRC History";
include("includes/head.php");
?>

	<div class="main-body-text " id="top">
		<h2 class="body-header   font-effect-3d-float">2012-2013</h2>

		<div id="about-us-content" style="width:100%" align="center">
			<div align="center" style="width:100%" class="content">
				
				<img style="width:506px;float: right;padding-left:20px" class="full_mobile" src="http://www.team3389.info/resources/TeamPic2013.jpg" alt="team"></img>

				<h2 class="body-header hvr-grow">2013 Game Animation - <a href="http://www.youtube.com/watch?v=wa5MGEZNrf0" target="_blank">Ultimate Ascent</a></h2>

				<div class="text">
					<p># Students: 24</p>
					<p>Regional Attended: Chesapeake Regional</p>

					<p>We placed 27 of 64 Teams registered</p>

					<p align="left">We had a great start with half the team being new members, many of whom were in the 9th and 10th grade. It`s great to have these new students with new energy and new ideas, it should be a great year!</p>

					<p>We started out the regional competition in first place by the third round, we dropped to 7th by the end of round 6 and day one was complete. Day two we had two matches and did not fare so well although the last match was our best ever.</p>

					<p>The last match we scored 18 autonomous points, 33 teleop points and a 10 point climb for a total of 61 points generated by "Sketchy" and the drive team!
					</p>
					
					<a style="float:left" href="history11.php">&lt;-Previous Year</a><a style="float:right" href="history13.php">Next Year-&gt;</a><p>&nbsp;</p>
				</div>
			</div>
		</div>
	</div>
	
<?php include("includes/footer.php"); ?>
</html>
