<!DOCTYPE html>
<?php include("includes/head.php");?>
	<div class="main-body-text " id="top">
		<h2 class="body-header   font-effect-3d-float">2013-2014</h2>
		
		<div id="about-us-content" style="width:100%" align="center">
			<div align="center" style="width:100%" class="content">
			
				<img style="width:506px; float: right;padding-left:20px" src="resources/TeamPic2015.jpg" alt="team"></img>

				<h2 class="body-header hvr-grow">2015 Game Animation - <a href="https://www.youtube.com/watch?v=W6UYFKNGHJ8">Recycle Rush</a></h2>

				<p># Students: 25</p>
				<p>Regional Attending: Chesapeake Regional</p>

				<p>We place 39th out of all the teams attending</p>

				<p align="left">Our team did good overall with many new students and some old.
					Overall we did very well at the competition even though we placed lower than usual.</p>
					Overall we did very well at the competition even though we placed lower than usual.</p>
			</div>
		</div>
	</div>

<!--Next Box-------------------------------------------------------------------------------------------------------------------------------------->

	<div class="main-body-text " id="top">
		<h2 class="body-header font-effect-3d-float">2013-2014</h2>
		
		<div id="about-us-content" style="width:100%" align="center">
			<div align="center" style="width:100%" class="content">
				<img style="width:506px;float: left;padding-right:20px" src="resources/TeamPic2014-small.jpg" alt="team"></img>

				<h2 class="body-header hvr-grow">2014 Game Animation - <a href="http://www.youtube.com/watch?v=f5zWzICG5to">Ariel Assist</a></h2>

				<p># Students: 30</p>
				<p>Regional Attending: Chesapeake Regional</p>

				<p>April 3rd - 5th</p>

				<p>We placed 19th out of all the teams attending</p>

				<p align="left">We have a great team with many veterans and new students all excited to build the robot for this year`s game Aerial Assist.</p>

			</div>
		</div>
	</div>

<!--Next Box-------------------------------------------------------------------------------------------------------------------------------------->

	<div class="main-body-text " id="top">
		<h2 class="body-header   font-effect-3d-float">2012-2013</h2>

		<div id="about-us-content" style="width:100%" align="center">
			<div align="center" style="width:100%" class="content">
				
				<img style="width:506px;float: right;padding-left:20px" src="http://team3389.info/img/2013-regional-team-picture.jpg" alt="team"></img>

				<h2 class="body-header hvr-grow">2013 Game Animation - <a href="http://www.youtube.com/watch?v=wa5MGEZNrf0">Ultimate Ascent</a></h2>

				<p># Students: 24</p>
				<p>Regional Attended: Chesapeake Regional</p>

				<p>We placed 27 of 64 Teams registered</p>

				<p align="left">We had a great start with half the team being new members, many of whom were in the 9th and 10th grade. It`s great to have these new students with new energy and new ideas, it should be a great year!<br><br>

					We started out the regional competition in first place by the third round, we dropped to 7th by the end of round 6 and day one was complete. Day two we had two matches and did not fare so well although the last match was our best ever.<br><br>

					The last match we scored 18 autonomous points, 33 teleop points and a 10 point climb for a total of 61 points generated by "Sketchy" and the drive team!
				</p>

			</div>
		</div>
	</div>

<!--Next Box------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>

	<div class="main-body-text " id="top">
		<h2 class="body-header   font-effect-3d-float">2011-2012</h2>
		
		<div id="about-us-content" style="width:100%" align="center">
			<div align="center" style="width:100%" class="content">
					
				<img style="width:506px;float: left;padding-right:20px" src="http://team3389.info/img/teampic-2012-sm.jpg" alt="team"></img>

				<h2 class="body-header hvr-grow">2012 Game Animation - <a href="http://www.youtube.com/watch?v=nOXsdhZZSdM">Rebound Rumble</a></h2>

				<p># Students: 20</p>
				<p>Regional Attended: Chesapeake Regional</p>

				<p>Placed 17th out of 63 teams present</p>

				<p align="left">The team name was changed from Strikeforce to RoboSpectrum and the visual arts department was kind enough to design a great logo for us. After a great, albeit busy build season the team ended up with a robot that was able to shoot baskets autonomously or with a driver.<br><br>

					Upon arrival to the competition Mr. Murphy showed up with a combination of a minor programming oversite and 2 electronics malfunctions which hurt our practice rounds and our standings in the first half of the competition. The team persevered and fixed most of the issues, eventually clawing their way up to 8th place. Unfortunately another malfunction in the last qualifying round caused the robot the sieze up, knocking us down to 17th place.<br><br>

					With all of the issues we faced the team continued to be optimistic and in the end had our highest ranking yet. 
				</p>

			</div>
		</div>
	</div>

<!--Next Box-------------------------------------------------------------------------------------------------------------------------------------->

	<div class="main-body-text " id="top">
		<h2 class="body-header   font-effect-3d-float">2010-2011</h2>
		
		<div id="about-us-content" style="width:100%" align="center">
			<div align="center" style="width:100%" class="content">
		
				<img style="width:506px;float:right;padding-left:20px" src="http://team3389.info/img/teampic-2011-sm.jpg" alt="team"></img>

				<h2 class="body-header hvr-grow">2011 Game Animation - <a href="http://www.youtube.com/watch?v=bk0QuuYLxqo">LogoMotion</a></h2>

				<p># Students: 20</p>
				<p>Regional Attending: Chesapeake Regional</p>

				<p>Placed 36th out of 60 teams present</p>

				<p align="left">The team was able to build a robot that performed the game tasks quite well, and our mini-bot performed above expectations. During the event we learned about Murphy`s Law when our mini-bot that previously had had no issues started burning out motors and releasing "the magic smoke". The robot performed consistently well regardless of who was driving it. Unfortunately we did not have autonomous code so we missed out on those possible points. Even with these hurdles the team was able to place 36th overall. </p>

			</div>
		</div>
	</div>

<!--Next Box-------------------------------------------------------------------------------------------------------------------------------------->

	<div class="main-body-text " id="top">
		<h2 class="body-header   font-effect-3d-float">2009-2010</h2>

		<div id="about-us-content" style="width:100%" align="center">
			<div align="center" style="width:100%" class="content">
				
				<img style="width:506px;float:left;padding-right:20px" src="http://team3389.info/img/teampic-2011-sm.jpg" alt="team"></img>

				<h2 class="body-header hvr-grow">2010 Game Animation - <a href="http://www.youtube.com/watch?v=IEHAj3EmpMw">BreakAway</a></h2>

				<p># Students: 16</p>
				<p>Regional Attending: Chesapeake Regional</p>

				<p>Placed 28th out of 60 teams present</p>

				<p align="left">The year 2009 marked the birth of team 3389. The team started with a late December phone call between Chris Thompson of Eastern Shore Robotics (Now called Tec Hub) and David Miles, the Parkside Electronics Teacher. He immediately recruited Mr. Steve Jenkins (Manufacturing Teacher), and Mrs. Jennifer Miles (Teaching Assistant). Mr. Rick Jones (Computer Repair Teacher), was recruited after the build season. The students were assembled very rapidly -just one week prior to kickoff. The team consisted of twelve Electronics students, two manufacturing students, and one student who moved here from Texas with his mother (Michelle Kosin) who also became a mentor towards the end of build season.
					<br><br>
					It was a rough year for the team as everyone was new to building robots. The team also lost two weeks of the six week build season due to the January snow storms which hit the Eastern United States. Even with a late start and only four weeks to build and ship the robot, our robot (named Ratchet) was completed on time and performed very well against the others at the Chesapeake Regional held in Baltimore. The robot was built to play Soccer. Ratchet made many goals during the competitions. The sleek robot design with its two large scooter wheels performed like a seasoned veteran. Ratchet`s performance, coupled with teamwork, safety, and professionalism demonstrated by our students in the pit area caught the eyes of the judges and other officials as we were awarded the coveted prize of Rookie All-Star which granted us a spot at the 2010 Championships in the Georgia Dome in Atlanta. We also won the Highest Ranking Rookie Seed Award.
					<br><br>
					While in Atlanta, we competed against 344 robots from many different regionals and countries. Most of the robots were regional champions and other rookie all-stars. In the pit area, we were surrounded by many non- English speaking teams. It was an amazing opportunity for our students to interact with people of similar interests and skills from all over the world. Team 3389 competed in the Archimedes Division and finished 34th in a field of 86 international teams. </p>

			</div>
		</div>
	</div>
<?php include("includes/footer.php"); ?>
</html>